name: Documentation
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
    - main
    paths:
      - 'docs/**'
      - 'notebooks/**'
      - 'flasc/_flasc.py'
      - 'flasc/_sklearn.py'
      - 'flasc/prediction.py'
      - '.github/workflows/Docs.yml'
  workflow_dispatch:

jobs:
  pages:
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          sudo apt-get install -y pandoc

      - name: Prepare Examples
        run: |
          cd notebooks
          for FILE in *.ipynb; do 
            cp $FILE ../docs
          done
          cd ..

      - id: deployment
        uses: sphinx-notes/pages@v3
        with:
          cache: True
          checkout: False
