name: Documentation
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout FLASC
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v4
        with:
            python-version: 3.8
            cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          sudo apt-get install -y pandoc

      - name: Prepare Examples
        run: |
          cd notebooks
          for FILE in *.ipynb; do 
            # echo "   "${FILE} >> ../docs/examples.rst
            cp $FILE ../docs
          done
          cd ..

      - name: Build Docs and Commit
        uses: sphinx-notes/pages@v2
        with:
          requirements_path: ./docs/requirements.txt

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PUSH_TOKEN }}
          branch: gh-pages